/*
 * Copyright PWF Technology LLC
 */
package com.pwf.example.swing;

import com.pwf.example.controller.MovieController;
import com.pwf.example.model.Movie;
import com.pwf.mvcme.MvcFramework;
import com.pwf.mvcme.MvcMeView;
import com.pwf.mvcme.View;
import java.util.Collection;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mfullen
 */
public class MoviePanel extends javax.swing.JPanel implements
        View<Collection<Movie>>
{
    private MovieController controller;
    private MvcFramework mvcFramework;

    /**
     * Creates new form MoviePanel
     */
    public MoviePanel()
    {
        initComponents();

    }

    @Override
    public String getName()
    {
        return "Index";
    }

    public void update(Collection<Movie> movies)
    {
        DefaultListModel<Movie> defaultListModel = new DefaultListModel<Movie>();
        for (Movie movie : movies)
        {
            defaultListModel.addElement(movie);
        }
        this.jList1.setModel(defaultListModel);
    }

    public void addMovieClicked()
    {
        this.controller.create();
        this.controller.getView(MovieController.MOVIE_CREATE).setVisible(true);
    }

    public void editMovieClicked()
    {

        Movie selectedValue = (Movie) this.jList1.getSelectedValue();
        if (selectedValue != null)
        {
            this.controller.edit(selectedValue.getId());
            this.controller.getView(MovieController.MOVIE_EDIT).setVisible(true);
        }
    }

    public void deleteMovieClicked()
    {
        this.controller = this.mvcFramework.getController(MovieController.class);
        Movie selectedValue = (Movie) this.jList1.getSelectedValue();
        if (selectedValue != null)
        {
            this.controller.delete(selectedValue.getId());
        }
    }

    public MvcFramework getMvcFramework()
    {
        return this.mvcFramework;
    }

    public void setMvcFramework(MvcFramework cf)
    {
        this.mvcFramework = cf;

        this.controller = this.mvcFramework.getController(MovieController.class);
        this.mvcFramework.register(new ErrorMessage());
        this.mvcFramework.register(new ModifyMovie.CreateMovie());
        this.mvcFramework.register(new ModifyMovie.EditMovie());
        this.mvcFramework.register(new ModifyMovie.DeleteMovie());


        this.controller.index();
    }

    static class ErrorMessage extends MvcMeView<String>
    {
        public void update(String t)
        {
            JOptionPane.showMessageDialog(null, t);
        }

        @Override
        public String getName()
        {
            return View.ERROR_VIEW_ID;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Movie List"));
        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setDividerSize(15);
        jSplitPane1.setDoubleBuffered(true);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(650, 500));
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(650, 500));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jButton1.setText("Add Movie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit Movie");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete Movie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        this.addMovieClicked();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        this.editMovieClicked();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        this.deleteMovieClicked();
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
